# Generated by Django 5.0 on 2024-02-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.CharField(choices=[('', '-- Select Option --'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='new_renew',
            field=models.CharField(choices=[('', '-- Select Option --'), ('New', 'New'), ('Renew', 'Renew')], max_length=20),
        ),
    ]
